# Generated by Django 3.0.7 on 2020-06-18 20:18

import charity.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charity', '0006_auto_20200503_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['status', 'pick_up_date', 'update_date'], 'verbose_name': 'Dary', 'verbose_name_plural': 'Dary'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='institution',
            field=models.ForeignKey(on_delete=models.SET(charity.models.get_sentinel_institution), to='charity.Institution', verbose_name='Instytucja'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(charity.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
